on:
  pull_request:
    branches:
      - stage
    types: [opened, synchronize]
name: release-stage
jobs:
  release-stage:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Bump and commit alpha release'
        run: |
          git fetch origin
          git checkout -b ${GITHUB_HEAD_REF} origin/${GITHUB_HEAD_REF}
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx standard-version --prerelease alpha --skip.changelog --no-verify

      - name: 'Push changes to the opened pr branch'
        run: git push origin ${GITHUB_HEAD_REF}