on:
  push:
    branches:
      - main
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.release-pr.outputs.pr }}
    steps:
      - id: release-pr
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: test-release
          default-branch: main
          changelog-types: '[{"type":"feat","section":":sparkles:  Funcionalidades"},{"type":"fix","section":":nut_and_bolt:  Correções"},{"type":"docs","section":":blue_book:  Documentações"},{"type":"style","section":":lipstick:  Interface/Usabilidade"},{"type":"refactor","section":":lollipop:  Refatorações"},{"type":"perf","section":":steam_locomotive:  Melhorias de Performance"},{"type":"test","section":":chains:  Testes"},{"type":"build","section":":hammer_and_wrench: Configurações do Projeto"},{"type":"ci","hidden":true},{"type":"chore","hidden":true},{"type":"revert","hidden":true}]'
  merge-release:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - id: merge
        if: ${{ needs.release.outputs.pr }}
        uses: actions/github-script@v6
        with:
          script: |
            const pr = ${{ needs.release.outputs.pr }}
            await github.rest.pulls.merge({
              merge_method: "merge",
              owner: context.repo.owner,
              pull_number: pr.number,
              repo: context.repo.repo,
            })
